# Generated by Django 4.2 on 2023-05-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
