# Generated by Django 4.2 on 2023-05-29 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
