# Generated by Django 4.2 on 2023-07-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee'), ('employer', 'employer')], max_length=20),
        ),
    ]
