# Generated by Django 4.2 on 2023-05-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_alter_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='video',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo_image/%Y/%m/%d'),
        ),
    ]
