# Generated by Django 4.2 on 2023-10-16 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0004_remove_testimonial_video_testimonial_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='target_audience',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
