# Generated by Django 4.2 on 2023-10-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0005_testimonial_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='target_audience',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=50),
        ),
    ]
