# Generated by Django 4.2 on 2023-09-12 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assign', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')])),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('over_start_time', models.TimeField(blank=True, null=True)),
                ('over_end_time', models.TimeField(blank=True, null=True)),
                ('total_over_time', models.IntegerField()),
                ('double_over_time', models.IntegerField(blank=True, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(default='Temesgen', max_length=100)),
                ('sick', models.BooleanField(default=False)),
                ('no_show', models.BooleanField(default=False)),
                ('job_type', models.CharField(default='Temporary')),
                ('location_URL', models.URLField(blank=True, help_text='Enter the google maps link for the business location', null=True)),
                ('employee_conformation', models.BooleanField(default=False)),
                ('employer_conformation', models.BooleanField(default=False)),
                ('special_task', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeCard.dateassigned')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dateassigned',
            name='time_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeCard.timeassigned'),
        ),
    ]
