# Generated by Django 4.2 on 2023-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeCard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeassigned',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
