# Generated by Django 4.2 on 2023-09-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeCard', '0002_timeassigned_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='employee_conformation',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='employer_conformation',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='no_show',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='sick',
        ),
        migrations.CreateModel(
            name='ClockOutClockInManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_in', models.BooleanField(default=False)),
                ('employee_in_time', models.DateTimeField()),
                ('employee_out', models.BooleanField(default=False)),
                ('employee_out_time', models.DateTimeField(auto_now=True)),
                ('employee_conformation', models.BooleanField(default=False)),
                ('employer_conformation', models.BooleanField(default=False)),
                ('sick', models.BooleanField(default=False)),
                ('no_show', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeCard.timecard')),
            ],
        ),
    ]
