# Generated by Django 4.2 on 2023-09-15 08:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeCard', '0003_remove_timecard_employee_conformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockoutclockinmanagement',
            old_name='employee_in',
            new_name='break_in',
        ),
        migrations.RenameField(
            model_name='clockoutclockinmanagement',
            old_name='employee_out',
            new_name='break_out',
        ),
        migrations.RemoveField(
            model_name='clockoutclockinmanagement',
            name='employee_in_time',
        ),
        migrations.RemoveField(
            model_name='clockoutclockinmanagement',
            name='employee_out_time',
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='break_in_out_time_cycle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='break_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='break_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='clock_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='clock_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='clock_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='clock_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='net_working_hour',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='over_time_clock_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='over_time_clock_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='over_time_clock_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='over_time_clock_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='over_time_cycle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='total_break_in_out_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='total_clock_in_out_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='clockoutclockinmanagement',
            name='total_over_time_clock_in_out_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='timecard',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('panging', 'panging'), ('complete', 'complete')], default='panging'),
        ),
    ]
