# Generated by Django 4.2 on 2023-08-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedJobs',
        ),
    ]
