# Generated by Django 4.2 on 2023-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracceptedpolicies',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
