# Generated by Django 4.2 on 2023-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_useracceptedpolicies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracceptedpolicies',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
