# Generated by Django 4.2 on 2023-05-26 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_alter_useracceptedpolicies_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('apartment', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('nevada', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=20)),
                ('home_phone', models.CharField(max_length=20)),
                ('work_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
