# Generated by Django 4.2 on 2023-05-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_basicinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='nevada',
        ),
    ]
