# Generated by Django 4.2 on 2023-05-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companyPolices_completed',
            field=models.BooleanField(default=False),
        ),
    ]
