# Generated by Django 4.2 on 2023-05-31 19:57

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_profile_companypolices_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
