# Generated by Django 4.2 on 2023-06-01 19:39

from django.db import migrations
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_basicinformation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='social_security_number',
            field=employee.models.SocialSecurityNumberField(max_length=11),
        ),
    ]
