# Generated by Django 4.2 on 2023-06-06 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_personal_social_security_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='languages',
        ),
        migrations.AddField(
            model_name='personal',
            name='languages',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('it', 'Italian'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('tl', 'Tagalog'), ('fa', 'Persian'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('he', 'Hebrew'), ('pa', 'Punjabi'), ('ta', 'Tamil'), ('mr', 'Marathi'), ('tr', 'Turkish'), ('th', 'Thai'), ('ne', 'Nepali'), ('sw', 'Swahili'), ('am', 'Amharic'), ('el', 'Greek'), ('nl', 'Dutch'), ('cs', 'Czech'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('ro', 'Romanian')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
