# Generated by Django 4.2 on 2023-06-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_personal_languages_personal_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='languages',
        ),
        migrations.AddField(
            model_name='personal',
            name='languages',
            field=models.ManyToManyField(to='employee.language'),
        ),
    ]
