# Generated by Django 4.2 on 2023-06-06 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0012_remove_personal_languages_personal_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('army', 'Army'), ('Navy', 'Navy'), ('marines', 'Marines'), ('coast-guard', 'Coast Guard'), ('air-force', 'Air Force'), ('others', 'Others')], max_length=50)),
                ('rank', models.CharField(choices=[('', 'Select Rank'), ('E-1 Seaman recruit', 'E-1 Seaman recruit'), ('E-2 Seaman apprentice', 'E-2 Seaman apprentice'), ('E-3 Seaman', 'E-3 Seaman'), ('E-4 Petty Officer 3rd class', 'E-4 Petty Officer 3rd class'), ('E-5 Petty Officer 2nd class', 'E-5 Petty Officer 2nd class'), ('E-6 Petty Officer 1st class', 'E-6 Petty Officer 1st class'), ('E-7 Chief Petty Officer', 'E-7 Chief Petty Officer'), ('E-8 Senior Chief Petty Officer', 'E-8 Senior Chief Petty Officer'), ('E-9 Master Chief Petty Officer', 'E-9 Master Chief Petty Officer'), ('E-9 Command Master Chief Petty Officer', 'E-9 Command Master Chief Petty Officer'), ('E-9 Master Chief Petty Officer of the Navy', 'E-9 Master Chief Petty Officer of the Navy'), ('W-2 Chief Warrant Officer 2', 'W-2 Chief Warrant Officer 2'), ('W-3 Chief Warrant Officer 3', 'W-3 Chief Warrant Officer 3'), ('W-4 Chief Warrant Officer 4', 'W-4 Chief Warrant Officer 4'), ('W-5 Chief Warrant Officer 5', 'W-5 Chief Warrant Officer 5'), ('O-1 Ensign', 'O-1 Ensign'), ('O-2 Lieutenant Junior Grade', 'O-2 Lieutenant Junior Grade'), ('O-3 Lieutenant', 'O-3 Lieutenant'), ('O-4 Lieutenant Commander', 'O-4 Lieutenant Commander'), ('O-5 Commander', 'O-5 Commander'), ('O-6 Captain', 'O-6 Captain'), ('O-7 Rear Admiral Lower Half', 'O-7 Rear Admiral Lower Half'), ('O-8 Rear Admiral', 'O-8 Rear Admiral'), ('O-9 Vice Admiral', 'O-9 Vice Admiral'), ('O-10 Admiral', 'O-10 Admiral'), ('O-11 Fleet Admiral', 'O-11 Fleet Admiral'), ('Other', 'Other')], max_length=100)),
                ('discharge_year', models.DateField(verbose_name='discharge year')),
                ('duty_flag', models.CharField(choices=[('ActiveDuty', 'Active Duty'), ('NonActive', 'Non Active')], max_length=50)),
                ('certification_license', models.FileField(upload_to='certificationsMilitary/')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
