# Generated by Django 4.2 on 2023-06-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_military_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='military',
            name='certification_license',
        ),
        migrations.RemoveField(
            model_name='military',
            name='slug',
        ),
        migrations.CreateModel(
            name='CertificationLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('certification_file', models.FileField(upload_to='certificationsMilitary/')),
                ('military', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.military')),
            ],
        ),
    ]
