# Generated by Django 4.2 on 2023-06-10 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0016_military_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='certification_license',
            field=models.FileField(default=django.utils.timezone.now, upload_to='certificationsMilitary/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='military',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='military',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CertificationLicense',
        ),
    ]
