# Generated by Django 4.2 on 2023-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_type',
            field=models.CharField(choices=[('elementary', 'Elementary School'), ('middle', 'Middle School'), ('high', 'High School'), ('college', 'College/University'), ('other', 'Other')], max_length=20),
        ),
    ]
