# Generated by Django 4.2 on 2023-06-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_category_position_skill_employeepreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='salary_type',
            field=models.CharField(choices=[('annual', 'Annual Salary'), ('monthly', 'Monthly Salary'), ('twoWeeks', 'Two Weeks Salary'), ('weekly', 'Weekly Salary'), ('daily', 'Daily Rate'), ('hourly', 'Hourly Wage'), ('commission', 'Commission'), ('bonus', 'Bonus'), ('profit_sharing', 'Profit Sharing'), ('other', 'Other')], max_length=20),
        ),
    ]
