# Generated by Django 4.2 on 2023-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_employeepreferences_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract/Freelance'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('remote', 'Remote/Telecommute'), ('shift-based', 'Shift-based'), ('volunteer', 'Volunteer'), ('consultant', 'Consultant'), ('permanent', 'Permanent'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=20),
        ),
    ]
