# Generated by Django 4.2 on 2023-06-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_alter_employeepreferences_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepreferences',
            name='skills',
        ),
        migrations.AddField(
            model_name='employeepreferences',
            name='skills',
            field=models.ManyToManyField(to='employee.skill'),
        ),
    ]
