# Generated by Django 4.2 on 2023-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_remove_employeepreferences_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='can_relocation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
