# Generated by Django 4.2 on 2023-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_employeepreferences_can_relocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_created',
            field=models.BooleanField(default=False),
        ),
    ]
