# Generated by Django 4.2 on 2023-06-23 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0032_alter_employeepreferences_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_test', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('in-progress', 'In Progress'), ('pending', 'Pending'), ('success', 'Success'), ('skipped', 'Skipped'), ('started', 'Started'), ('lookup', 'lookup')], default='lookup', max_length=20)),
                ('result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeepreferences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
