# Generated by Django 4.2 on 2023-06-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_alter_skillsettestresult_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsettestresult',
            old_name='state',
            new_name='states',
        ),
    ]
