# Generated by Django 4.2 on 2023-07-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_profile_onprogressskilltest_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsettestresult',
            name='conformation',
            field=models.CharField(default='Id12565874', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeepreferences',
            name='job_type',
            field=models.CharField(choices=[('temp', 'Temp'), ('temp-Perm', 'Temp-Perm'), ('perm', 'Perm'), ('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract/Freelance'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('remote', 'Remote/Telecommute'), ('shift-based', 'Shift-based'), ('volunteer', 'Volunteer'), ('consultant', 'Consultant'), ('permanent', 'Permanent'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=20),
        ),
    ]
