# Generated by Django 4.2 on 2023-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_skillsettestresult_conformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety_Video_and_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Safety_Video_image/%Y/%m/%d')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Safety_Video_and_Test_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skillsettestresult',
            name='states',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('pending', 'Pending'), ('success', 'Success'), ('skipped', 'Skipped'), ('started', 'Started')], default='started', max_length=20),
        ),
    ]
