# Generated by Django 4.2 on 2023-07-13 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0040_safetytestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videoResumes/%Y/%m/%d')),
                ('tell_about_you', models.TextField(blank=True, help_text='Share a fascinating fact or story about yourself.', max_length=300, null=True)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RettingCommenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retting', models.SmallIntegerField(default=1)),
                ('tag', models.CharField(choices=[('', 'Select Rank'), ('E-1 Seaman recruit', 'E-1 Seaman recruit'), ('E-2 Seaman apprentice', 'E-2 Seaman apprentice'), ('E-3 Seaman', 'E-3 Seaman'), ('E-4 Petty Officer 3rd class', 'E-4 Petty Officer 3rd class'), ('E-5 Petty Officer 2nd class', 'E-5 Petty Officer 2nd class'), ('E-6 Petty Officer 1st class', 'E-6 Petty Officer 1st class'), ('E-7 Chief Petty Officer', 'E-7 Chief Petty Officer'), ('E-8 Senior Chief Petty Officer', 'E-8 Senior Chief Petty Officer'), ('E-9 Master Chief Petty Officer', 'E-9 Master Chief Petty Officer'), ('E-9 Command Master Chief Petty Officer', 'E-9 Command Master Chief Petty Officer'), ('E-9 Master Chief Petty Officer of the Navy', 'E-9 Master Chief Petty Officer of the Navy'), ('W-2 Chief Warrant Officer 2', 'W-2 Chief Warrant Officer 2'), ('W-3 Chief Warrant Officer 3', 'W-3 Chief Warrant Officer 3'), ('W-4 Chief Warrant Officer 4', 'W-4 Chief Warrant Officer 4'), ('W-5 Chief Warrant Officer 5', 'W-5 Chief Warrant Officer 5'), ('O-1 Ensign', 'O-1 Ensign'), ('O-2 Lieutenant Junior Grade', 'O-2 Lieutenant Junior Grade'), ('O-3 Lieutenant', 'O-3 Lieutenant'), ('O-4 Lieutenant Commander', 'O-4 Lieutenant Commander'), ('O-5 Commander', 'O-5 Commander'), ('O-6 Captain', 'O-6 Captain'), ('O-7 Rear Admiral Lower Half', 'O-7 Rear Admiral Lower Half'), ('O-8 Rear Admiral', 'O-8 Rear Admiral'), ('O-9 Vice Admiral', 'O-9 Vice Admiral'), ('O-10 Admiral', 'O-10 Admiral'), ('O-11 Fleet Admiral', 'O-11 Fleet Admiral'), ('Other', 'Other')], max_length=50)),
                ('comments', models.TextField(blank=True, help_text='comments me', max_length=300, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
