# Generated by Django 4.2 on 2023-07-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0043_alter_videoresume_tell_about_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresume',
            name='states',
            field=models.CharField(choices=[('in-progress', 'InProgress'), ('pending', 'Pending'), ('activated', 'Activated')], default='pending', max_length=20),
        ),
    ]
