# Generated by Django 4.2 on 2023-07-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_videoresume_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresume',
            name='states',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('pending', 'pending'), ('activated', 'activated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoresume',
            name='tell_about_you',
            field=models.TextField(help_text='Share a fascinating fact or story about yourself.', max_length=600, null=True),
        ),
    ]
