# Generated by Django 4.2 on 2023-07-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0046_alter_safetytestresult_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Background_Check_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Background_Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='certificationsBackground/')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('states', models.CharField(choices=[('InProgress', 'InProgress'), ('pending', 'pending'), ('activated', 'activated')], default='pending', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
