# Generated by Django 4.2 on 2023-07-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_profile_background_check_completed_background_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='background_check',
            name='expiration_states',
            field=models.CharField(default='valid', max_length=50),
        ),
        migrations.AlterField(
            model_name='background_check',
            name='states',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
