# Generated by Django 4.2 on 2023-07-26 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0051_bankaccount_slug_card_slug_checkbyemail_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(help_text='Enter valid account number to avoid delay.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(help_text='Enter valid routing number to avoid delay.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.SmallIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(limit_value=5), django.core.validators.MaxLengthValidator(limit_value=5)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='checkbyemail',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='checkbyemail',
            name='use_basicInfo_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ewallet',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
