# Generated by Django 4.2 on 2023-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CheckByMailBtn_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bankAccountBtn_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='cardBtn_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eWalletBtn_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(help_text='Enter valid routing number to avoid delay.', max_length=9),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.SmallIntegerField(),
        ),
    ]
