# Generated by Django 4.2 on 2023-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0055_ridepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepreferences',
            name='work_arrangement_preference',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ON_SITE', 'On-site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeepreferences',
            name='location',
            field=models.CharField(choices=[('home_proximity', 'Proximity to Home/Family'), ('job_opportunity', 'Job Market and Opportunities')], default='HOME_PROXIMITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='skillsettestresult',
            name='conformation',
            field=models.CharField(default='j1o2b3d3og5g', max_length=20),
        ),
    ]
