# Generated by Django 4.2 on 2023-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0057_alter_skillsettestresult_conformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='job_type',
            field=models.CharField(choices=[('Temp', 'Temporary'), ('Temp-Perm', 'Temporary to Permanent'), ('Perm', 'Permanent'), ('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract/Freelance'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('remote', 'Remote/Telecommute'), ('shift-based', 'Shift-based'), ('consultant', 'Consultant'), ('other', 'Other')], max_length=20),
        ),
    ]
