# Generated by Django 4.2 on 2023-09-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferences',
            name='job_type',
            field=models.CharField(choices=[('', 'Select Job Type'), ('Temp', 'Temporary'), ('Temp-Perm', 'Temporary to Permanent'), ('Perm', 'Permanent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeepreferences',
            name='work_arrangement_preference',
            field=models.CharField(choices=[('', 'Select Work Arrangement Preference'), ('REMOTE', 'Remote'), ('ON_SITE', 'On-site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=10),
        ),
    ]
