# Generated by Django 4.2 on 2023-09-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0062_certificationlicense_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='one', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_type',
        ),
        migrations.AddField(
            model_name='education',
            name='custem_school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='custem_school_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('associate_of_arts', 'Associate of Arts (A.A.)'), ('associate_of_science', 'Associate of Science (A.S.)'), ('associate_of_applied_science', 'Associate of Applied Science (A.A.S.)'), ('associates_degree_in_nursing', 'Associates Degree in Nursing (ADN)'), ('bachelor_of_arts', 'Bachelor of Arts (B.A.)'), ('bachelor_of_science', 'Bachelor of Science (B.S.)'), ('bachelor_of_fine_arts', 'Bachelor of Fine Arts (BFA)'), ('bachelor_of_business_administration', 'Bachelor of Business Administration (BBA)'), ('bachelor_of_engineering', 'Bachelor of Engineering (B.E.)'), ('bachelor_of_architecture', 'Bachelor of Architecture (B.Arch)'), ('bachelor_of_music', 'Bachelor of Music (B.M.)'), ('doctor_of_medicine', 'Doctor of Medicine (M.D.)'), ('doctor_of_dental_surgery', 'Doctor of Dental Surgery (D.D.S.)'), ('doctor_of_pharmacy', 'Doctor of Pharmacy (Pharm.D.)'), ('doctor_of_veterinary_medicine', 'Doctor of Veterinary Medicine (D.V.M.)'), ('doctor_of_osteopathic_medicine', 'Doctor of Osteopathic Medicine (D.O.)'), ('doctor_of_nursing_practice', 'Doctor of Nursing Practice (DNP)'), ('doctor_of_philosophy', 'Doctor of Philosophy (Ph.D.)'), ('juris_doctor', 'Juris Doctor (J.D.)'), ('master_of_arts', 'Master of Arts (M.A.)'), ('master_of_science', 'Master of Science (M.S.)'), ('master_of_business_administration', 'Master of Business Administration (MBA)'), ('master_of_public_administration', 'Master of Public Administration (MPA)'), ('master_of_fine_arts', 'Master of Fine Arts (MFA)'), ('master_of_education', 'Master of Education (M.Ed.)'), ('master_of_social_work', 'Master of Social Work (MSW)'), ('master_of_architecture', 'Master of Architecture (M.Arch)'), ('master_of_music', 'Master of Music (M.M.)'), ('master_of_health_administration', 'Master of Health Administration (MHA)'), ('master_of_information_science', 'Master of Information Science (MIS)'), ('doctor_of_education', 'Doctor of Education (Ed.D.)'), ('doctor_of_psychology', 'Doctor of Psychology (Psy.D.)'), ('doctor_of_social_work', 'Doctor of Social Work (DSW)'), ('none', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='SchoolName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='two', max_length=100)),
                ('type_of_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.typeofschool')),
            ],
        ),
    ]
