# Generated by Django 4.2 on 2023-09-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0063_typeofschool_remove_education_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.ManyToManyField(related_name='school_name', to='employee.schoolname'),
        ),
        migrations.AddField(
            model_name='education',
            name='type_of_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.typeofschool'),
        ),
    ]
