# Generated by Django 4.2 on 2023-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0064_education_school_name_education_type_of_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeepreferences',
            name='job_type',
            field=models.CharField(choices=[('', 'Select Job Type'), ('Temporary', 'Temporary'), ('Temp-Perm', 'Temporary to Permanent'), ('Permanent', 'Permanent')], max_length=20),
        ),
    ]
