# Generated by Django 4.2 on 2023-09-05 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0060_alter_language_name'),
        ('employer', '0021_alter_jobrequisition_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeepreferences')),
                ('job_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobrequisition')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed'), ('in_cart', 'In Cart'), ('message', 'Message'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendedByAI.recommendedjobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
