# Generated by Django 4.2 on 2023-08-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendedByAI', '0004_alter_appliedjobhistory_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobhistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendedByAI.recommendedjobs'),
        ),
    ]
