# Generated by Django 4.2 on 2023-08-14 01:04

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='state',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telephone',
            field=models.CharField(default='phone', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='zip_code',
            field=models.CharField(default='89117', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Short description about your company.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
