# Generated by Django 4.2 on 2023-08-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_companyprofile_city_companyprofile_fax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='representative_name',
            new_name='representative_full_name',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(default='country', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Enter the Google Maps link for your location.', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='opening_hours',
            field=models.CharField(blank=True, help_text="Enter opening hours in the format: 'Weekend Hours (Mon-Fri 9:00 AM - 5:00 PM)' and 'Weekday Hours (Sat-Sun 3:00 AM - 2:00 PM).'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company_profile_video/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='zip_code',
            field=models.CharField(default='zip', max_length=10),
        ),
    ]
