# Generated by Django 4.2 on 2023-08-16 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_rename_representative_name_companyprofile_representative_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPoliciesAndTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profilebuildingcontroller',
            name='is_account_created',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmployerAcceptedPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('policies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employerpoliciesandterms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
