# Generated by Django 4.2 on 2023-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0007_jobrequisition_preference_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccode',
            name='position',
        ),
        migrations.AddField(
            model_name='soccode',
            name='position',
            field=models.ManyToManyField(related_name='soc', to='employee.position'),
        ),
    ]
