# Generated by Django 4.2 on 2023-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0008_remove_soccode_position_soccode_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='job_title',
            field=models.ManyToManyField(related_name='job_title', to='employee.position'),
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='soc_code',
        ),
        migrations.AlterField(
            model_name='soccode',
            name='position',
            field=models.ManyToManyField(related_name='soc_code', to='employee.position'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.CharField(default='1234'),
        ),
    ]
