# Generated by Django 4.2 on 2023-08-21 16:35

from django.db import migrations, models
import employer.models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_jobrequisition_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.CharField(blank=True, null=True, verbose_name=employer.models.SocCode),
        ),
    ]
