# Generated by Django 4.2 on 2023-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_jobrequisition_soc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequisition',
            name='soc_code',
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.ManyToManyField(to='employer.soccode'),
        ),
    ]
