# Generated by Django 4.2 on 2023-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0011_remove_jobrequisition_soc_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='category',
            new_name='industry',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='custom_required_skills',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timecard',
            name='employee_conformation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timecard',
            name='employer_conformation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timecard',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Enter the Google Maps link for your location.', null=True),
        ),
        migrations.AddField(
            model_name='timecard',
            name='massage',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='required_skills',
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.ManyToManyField(related_name='job_requisitions', to='employer.soccode'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='required_skills',
            field=models.ManyToManyField(to='employee.skill'),
        ),
    ]
