# Generated by Django 4.2 on 2023-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_rename_category_jobrequisition_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.ManyToManyField(blank=True, related_name='job_requisitions', to='employer.soccode'),
        ),
    ]
