# Generated by Django 4.2 on 2023-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_alter_jobrequisition_soc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.ManyToManyField(default='0000', related_name='job_SocCode', to='employer.soccode'),
        ),
    ]
