# Generated by Django 4.2 on 2023-08-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0014_alter_jobrequisition_soc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='job_title',
            field=models.ManyToManyField(related_name='jobTitle', to='employee.position'),
        ),
    ]
