# Generated by Django 4.2 on 2023-08-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0015_alter_jobrequisition_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequisition',
            name='soc_code',
        ),
        migrations.RemoveField(
            model_name='soccode',
            name='position',
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_SocCode', to='employer.soccode'),
        ),
        migrations.AddField(
            model_name='soccode',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc_code', to='employee.position'),
        ),
    ]
