# Generated by Django 4.2 on 2023-08-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0016_remove_jobrequisition_soc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='soc_code',
            field=models.CharField(blank=True, default='0000', null=True),
        ),
        migrations.AlterField(
            model_name='soccode',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soc_code', to='employee.position'),
        ),
    ]
