# Generated by Django 4.2 on 2023-08-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_alter_employeepreferences_job_type'),
        ('employer', '0017_alter_jobrequisition_soc_code_alter_soccode_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.category'),
        ),
    ]
