# Generated by Django 4.2 on 2023-09-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_alter_jobrequisition_soc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
