# Generated by Django 4.2 on 2023-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0022_alter_jobrequisition_min_degree_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='job_type',
            field=models.CharField(choices=[('', 'Select Job Type'), ('Temporary', 'Temporary'), ('Temp-Perm', 'Temporary to Permanent'), ('Permanent', 'Permanent')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TimeCard',
        ),
    ]
